version: '3.7'

services:
  spring-boot-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./demo:/app
    networks:
      - roachnet
    ports:
      - "9999:8080"
    depends_on:
      - cockroachdb1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cockroachdb1:26257/bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 

  cockroachdb1:
    image: cockroachdb/cockroach:v23.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "roach1:/cockroach/cockroach-data"
    networks:
      - roachnet
    entrypoint: /bin/sh -c "cockroach start-single-node --insecure && cockroach sql --insecure < /docker-entrypoint-initdb.d/init.sql"

networks:
  roachnet:

volumes:
  roach1:
